### ISSUE TITLE
Questions about changing the hand model

### ISSUE THREAD

**Issue by zihos** [christsa/dgrasp#5] opened 2022-11-21 10:37 UTC
Dear Sammy,

I would like to change or add another hand model in dgrasp.
Could you explain which part of the code is related to the hand model when you have time?

I would really appreciate it if you could tell me what part of the code should be checked and edited to change the hand model.

Best regards,
Jiho Park.

**Comment by christsa** [comment] 2022-11-21 13:03
Hi Jiho,

The hand model used in D-Grasp is stored [here](https://github.com/christsa/dgrasp/blob/main/rsc/mano/mano_mean.urdf).

In the code, it is loaded in the runner file at [this line](https://github.com/christsa/dgrasp/blob/59c6f6154c876a98eb2cd836db59e33355db5d57/raisimGymTorch/raisimGymTorch/env/envs/dgrasp/runner.py#L161).

If your hand model has a different structure, you also need to  adjust several things, depending on what your goal is:

- The number of joints [here](https://github.com/christsa/dgrasp/blob/main/raisimGymTorch/raisimGymTorch/env/envs/dgrasp/Environment.hpp#L809)
- The names of the body parts and collision bodies [here
](https://github.com/christsa/dgrasp/blob/59c6f6154c876a98eb2cd836db59e33355db5d57/raisimGymTorch/raisimGymTorch/env/envs/dgrasp/Environment.hpp#L825-L839)
- The size of the state space [here](https://github.com/christsa/dgrasp/blob/main/raisimGymTorch/raisimGymTorch/env/envs/dgrasp/Environment.hpp#L91)
- The labels are intended for MANO hands. If your hand model is structured differently, you will need to adjust the labels as well or do some remapping.

These are the most important steps. There are potentially more things you may need to change depending on your intentions.

Let me know if that works out or if you have more questions.

Best,
Sammy

**Comment by zihos** [comment] 2022-11-24 18:27
Dear Sammy, 
Thank you for your kind instruction!
It would be very helpful for me.

By the way, I would like to let you know there are missing files in the repository. There's no `texture_map.png` in `dgrasp/rsc/meshes_simplified/040_large_marker/`. Therefore, when the random obj demo selects `large_marker` obj, the demo quit.

Best regards,
Jiho Park.

**Comment by christsa** [comment] 2022-11-25 10:35
Hi Jiho,

Thanks for the pointer, I must have missed that one. Sorry for the inconvenience, it should be fixed now.

Best,
Sammy

**Comment by zihos** [comment] 2022-11-28 22:54
Thank you Sammy! 😊

**Comment by zihos** [comment] 2023-01-19 20:28
Hi Sammy,

I have some questions about changing the hand model in the dgrasp, so I reopened this issue.
I'd like to change mano model to MPL(modular prosthetic limb) model. [here is the MPL.xml](https://github.com/philtabor/PyBullet-Hand-Example/blob/master/MPL.xml)
Therefore, I changed the mano model source code parts you mentioned above to suit the MPL (such as contact_bodies, body_parts) on the `Environment.hpp` file.
Then, I run the command below
```
python raisimGymTorch/env/envs/dgrasp/runner.py
```

As the result, I got an error message as follows
```
Segmentation fault (core dumped)
```

But I couldn't find what is the main reason for this error.
Could you let me know if you have any guesses?

Thank you!
Best,
Jiho

**Comment by christsa** [comment] 2023-01-20 10:26
Hi Jiho,

It's very hard to tell, as segmentation fault is the most generic error you can get and it could be caused by many different things.
What I would suggest is that you first create a minimal example similar to [this file](https://github.com/christsa/dgrasp/blob/main/examples/src/mjcf/ant.cpp) to see and visualize whether your MuJoCo model can be correctly converted into RaiSim. 

Also did you take care of the following points  described above:
- adjust the size of the state space to the new model.
- make sure that the inputs (e.g. labels) and initializations in [runner.py](https://github.com/christsa/dgrasp/blob/main/raisimGymTorch/raisimGymTorch/env/envs/dgrasp/runner.py) are aligned with the new hand model.

**Comment by zihos** [comment] 2023-01-20 18:52
Hi Sammy,

Thank you for your answer!
I tried to run the examples you mentioned above, but I couldn't build the `MakeFile`.

``` shell
@Jiho:~/raisim/dgrasp/examples/build$ cmake .. -DCMAKE_PREFIX_PATH=~/raisim/raisim_build
-- raisim:
--   Version: 1.1.0
--   Includes: /home/mercury01/raisim/raisim_build/include
--   Libraries: raisim::raisimPng;raisim::raisimODE;raisim::raisimMine;raisim::raisim
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mercury01/raisim/dgrasp/examples/build
```

Here's my error message below.
``` shell
@Jiho:~/raisim/dgrasp/examples/build$ make
[  1%] Building CXX object CMakeFiles/mjcf_ant.dir/src/mjcf/ant.cpp.o
/home/mercury01/raisim/dgrasp/examples/src/mjcf/ant.cpp:4:10: fatal error: raisim/World.hpp: No such file or directory
	4 | #include "raisim/World.hpp"
  	|      	^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/mjcf_ant.dir/build.make:63: CMakeFiles/mjcf_ant.dir/src/mjcf/ant.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:128: CMakeFiles/mjcf_ant.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```
But I couldn't find what's the main reason for this error.
I changed the path of the `raisim hpp folder` but It didn't work also.
Could you let me know if you have any guesses?

Thank you! and Happy New Year!🎊
Best,
Jiho

**Comment by christsa** [comment] 2023-01-21 15:39
Did you change anything in the `ant.cpp` or `CMakeLists.txt` files?
This likely is an issue with your installation. If you didn't change these, maybe a fresh install following the installation guide is the best option.
I ran the commands you posted above in my setting and there were no issues.

Best,
Sammy

**Comment by christsa** [comment] 2023-01-23 10:12
Dear Jiho, 

I created a minimal example for you that loads your hand model. 
I first converted your MuJoCo model to a URDF file using [this repo](https://github.com/iory/mjcf2urdf).
You can find the URDF file [here](https://github.com/christsa/dgrasp/tree/main/rsc/mpl_hand).
[This file](https://github.com/christsa/dgrasp/blob/main/examples/src/server/mpl_hand.cpp) loads the hand in RaiSim. After building, there should be an executable in the build folder called "mpl_hand" that you can run.
The visualization should then look like this:
<img src="https://user-images.githubusercontent.com/32132810/214013943-6e49d679-5872-4f9d-8fa5-8fa937dc255a.png" width="400" height="280">

Let me know if it works for you.

Best,
Sammy

**Comment by christsa** [comment] 2023-01-24 16:07
Hi Jiho,

I'm glad it worked out.
I'll close the issue here, but feel free to reopen it should you run into any more problems.

Best,
Sammy

**Comment by zihos** [comment] 2023-01-24 23:42
Hi Sammy,

Thank you for your attention.
I reopened this issue because of some questions.

> Hi Jiho,
> 
> It's very hard to tell, as segmentation fault is the most generic error you can get and it could be caused by many different things. What I would suggest is that you first create a minimal example similar to [this file](https://github.com/christsa/dgrasp/blob/main/examples/src/mjcf/ant.cpp) to see and visualize whether your MuJoCo model can be correctly converted into RaiSim.
> 
> Also did you take care of the following points described above:
> 
> * adjust the size of the state space to the new model.
> * make sure that the inputs (e.g. labels) and initializations in [runner.py](https://github.com/christsa/dgrasp/blob/main/raisimGymTorch/raisimGymTorch/env/envs/dgrasp/runner.py) are aligned with the new hand model.
> 
> Best, Sammy

As follow your comment above, you said I have to adjust the size of the `state space`.
What is the meaning of `state space`? I wonder what's the meaning of the number `279` in order to adjust it to the new hand model.

Secondly, I tried to train the model with the new MPL hand model, but It was failed.
I think it's because of the labels of the inputs. Could you let me know how to make the `dexycb_train_labels`?
I'd like to make train labels for the new hand model. However, I couldn't find the generating labels code in the repo. 😭

I always feel appreciative of you.
Best,
Jiho.

**Comment by ksh960910** [comment] 2023-02-02 22:18
Hi Sammy, 

I have a similar question about making grasp labels from other datasets. It seems that the format of grasp labels from GraspTTA differs from the format of dgrasp's. It would be great to know whether there's a code for it or a way to convert it.


Best regards,
Joe

**Comment by christsa** [comment] 2023-02-07 11:54
Dear all,

Apologies for the late reply, I was busy with rebuttals.

@zihos the state space of 279 consists of the components described in the paper: hand pose (51) and velocities (51), object pose (6) and velocities (6), object displacement (3), vert. distance to table (3), goal position distances (63), goal pose distances (48), contact goal vector (48)

I'm working on a script that will create the labels. 
In the meantime, here are the steps I followed:
1. Get hand object grasp poses (e.g. from DexYCB, GraspTTA, etc.) 
2. Convert the hand and object pose to the correct format for the simulation. The hand takes Euler angles as input.
3. To get the goal vectors, each component has to be computed seperately:
    a) goal pose: use the angles from step 2.
    b) goal positions: use forward kinematics to compute the hand's global 3D joint positions. There are multiple ways to do this. For MANO, one could feed it through MANO layer to get the positions. In D-Grasp, I just set the hand pose into the configuration from step 2. and recorded the global positions of the joints.
   c) goal contacts: to get the goal contacts, I used the following [computation](https://github.com/christsa/dgrasp/blob/baa14c87a622e6201d63ff0c1837919af1c693a2/raisimGymTorch/raisimGymTorch/helper/runner_explanation.py#L290-L320). Essentially, it looks at the closest vertex of the object mesh for each hand joint. If the distance of the vertex to the joint is below a certain threshold, the joint should be in contact.

I will keep you posted about the script for label generation.

Best,
Sammy

**Comment by zihos** [comment] 2023-02-17 13:29
Dear Sammy,
Thank you for your reply!

I'm trying to fit the grasp labels from the MANO model to the MPL model but it's quite difficult without your script for label generation...😭
I'm waiting for your data generation code (grasp label generation script)!

Thank you!

Best regards,
Jiho

**Comment by christsa** [comment] 2023-02-18 14:14
Hi Jiho,

I've added a file that converts a grasp label from DexYCB (given in MANO PCA representation as provided [here](https://github.com/NVlabs/dex-ycb-toolkit)) into a Dgrasp label: [conversion file](https://github.com/christsa/dgrasp/blob/main/raisimGymTorch/raisimGymTorch/helper/convert_label.py)

However, I'm not sure it directly translates to the different hand model you have, because I was using MANO layer to compute the forward kinematics and retrieve the vertices for the contacts. Since most relevant datasets also use MANO representation, it directly translates to the approximated MANO model I made for RaiSim. 

In your case, you should first create a mapping between your hand model and MANO. You could then either try to use the already existing labels, but only keep the information for the joints that exist in both hand models. Or you can recreate the labels by either implementing something like a MANO layer yourself, or create a workaround by using RaiSim.

For the latter, you should:
1. Apply the rotations to the respective joints of your hand model (using the mapping) in RaiSim.
2. Record the necessary information in RaiSim with your hand model (i.e., 3D joint positions and relative joint positions, contacts, etc.).
3. Store the information in new labels.
4. Reduce observation space in the environment according to your hand model.
5. Retrain with your model and labels.

Do these steps make sense to you?

Best,
Sammy

**Comment by christsa** [comment] 2023-09-02 13:02
Feel free to reopen this issue if you have any more questions on this problem.

**Closed by christsa** 2023-09-02 13:02 UTC
